### ISSUE TITLE
128 dimensional feature vector

### ISSUE THREAD

**Issue by kiriace** [ekzhu/datasketch#100]
how can i use minHash lsh for calculating the nearest vector ( in terms of distance ) to the input vector .....
all vectors are 128 dimensional with range of each element between 0 and 1 ...
will weightedhashgenerator give me the same results as euclidean distance LSH

**Comment by ekzhu** [comment]
MinHash won't give you nearest neighbours for L2 LSH. You may be looking for [L2 LSH](https://github.com/ekzhu/lsh).

**Comment by kiriace** [comment]
Got it . jaccard similarity wont work with vectors . thank you
