### ISSUE TITLE
MinHashLSH method query has a bug

### ISSUE THREAD

**Issue by lolgolflol** [ekzhu/datasketch#105]
```
set1 = set(["a", "b"])
set2 = set(["a", "b", "c", "d", "e"])
m1 = MinHash(num_perm=128)
m2 = MinHash(num_perm=128)
lsh = MinHashLSH(threshold=0.5, num_perm=128)
lsh.insert("m1", m1)
print(m1.jaccard(m2))
result = lsh.query(m2)
result is not found
```
This case work, because  they are duplicate  less than 50%
and then I change some charactor to be
```
set1 = set(["a", "b"])
set2 = set(["a", "b", "c", "d", "f"])
m1 = MinHash(num_perm=128)
m2 = MinHash(num_perm=128)
lsh = MinHashLSH(threshold=0.5, num_perm=128)
lsh.insert("m1", m1)
print(m1.jaccard(m2))
result = lsh.query(m2)
query found  m1  
```
I just change letter e to be letter f

**Comment by ekzhu** [comment]
MinHashLSH is an approximate index, which means there will be false positive and false negative. Typically the caller of this library will do a "post-processing" to verify the returned results to remove false positives. For reducing false negative you can decrease the threshold to get more candidates, and use a higher threshold in post-processing.

**Comment by lolgolflol** [comment]
Thank you.
