### ISSUE TITLE
Getting Minhash from Redis

### ISSUE THREAD

**Issue by Erlix322** [ekzhu/datasketch#106]
Hi,

currently I'm not able to get the minhashs back from MinHashLSH. How do I get them to measure distances.

Inserting is straightforward doable like this:
```
m = MinHash(num_perm=128) 
        for d in tokenized:
            m.update(d.encode('utf8'))
lsh.insert(key,m)
```
But when it comes to getting the values back I don't see how it's done. I would expect something like this:

```
minhash = lsh.get(key) #should return minhash
minhash2 = lsh.get(key2) #should return minhash2
minhash.jaccard(minhash2)
```
should I store the values in a separate storage?

**Comment by ekzhu** [comment]
You are absolutely right -- we didn't implement `lsh.get(key)`.
