### ISSUE TITLE
A way to work with a large LSH Forest?

### ISSUE THREAD

**Issue by gmanlan** [ekzhu/datasketch#111]
I understand MinHash can be persisted using storage layers, however I'm curious about the LSH Forest itself. In one experiment with 3M samples, a pickled forest is 6 GB big, so I'm afraid it doesn't scale once I run out of RAM.

If the MinHashes use something like Cassandra, will that mean the resulting Forest will be small when it's pickled for persistence? If not, any idea on how a forest can be created/persisted in such a way that it's not limited by the available memory?

**Comment by ekzhu** [comment]
@gmanlan thanks for your issue. Currently  MinHashLSHForest does not support external storage. You can use MinHashLSH. You can set a smaller threshold for the index and rank the results in your own code afterward.

**Comment by gmanlan** [comment]
@ekzhu thanks for confirming. I'll look into your suggestion. Cheers,
