### ISSUE TITLE
LSH for Feature vectors of ConvNet

### ISSUE THREAD

**Issue by mrgransky** [ekzhu/datasketch#113]
Given a pre-trained CNN model, I extract feature vectors `FV_R` for reference images as follows:
```
FV_R = [       [-8.2, -52.2, 9.07, -1.1, -0.08, -9.1, ........, -4.11], 
               [7.8, -3.8, 6.4, -4.27, -2.2, -5.0, ............., 3.6], 
               [-1.2, -0.8, 49.3, 1.73, -1.74, -7.1, ..........., 2.41],
               [-1.2, -.8, 49.3, 0.6, -1.24, -1.04, .........., -2.06],
               .
               .
               .
               [-1.2, -.8, 49.3, 12.77. -2.2, -5.0, .........., -51.1]
       ]
```
 and `FV_Q` for query images :
```
FV_Q = [       [-0.13, 2.6, -3.7, -0.5, -1.02, -0.6, ........, -0.11], 
               [0.3, -3.8, 6.4, -1.6, -2.2, -5.0, ............., 0.97], 
               [-6.4, -0.08, 8.0, 7.3, -8.07, -5.6, ..........., 0.01],
               [-6.09, -.8, 0.5, -8.9, -0.74, -0.08, .........., -8.9],
               .
               .
               .
               [-1.2, -.8, 49.3, 12.77. -2.2, -5.0, .........., -51.1]
       ]
```
The size info:

Reference images:
```
>>> FV_R.shape
(3450, 64896)
```
Query images:
```
>>> FV_Q.shape
(1200, 64896)
```

I would like to apply LSH to reduce the dimensionality of `FV_R` and `FV_Q` for similarity computations!

Can I use `datasketch`  in python doing that? 

Because I have mostly seen examples working with text recommendations for example [here](https://www.learndatasci.com/tutorials/building-recommendation-engine-locality-sensitive-hashing-lsh-python/) having binary (`0/1`) shingle matrix!

Cheers,

**Comment by ekzhu** [comment]
MinHash is probably not useful for handling dense vectors like what you have here. You will need something other algorithms such as PCA etc. For search index you can try HNSW.
