### ISSUE TITLE
Persistent storage on MongoDB

### ISSUE THREAD

**Issue by blah-crusader** [ekzhu/datasketch#117]
Hi guys,

Question, I'd like to store a MinHashLSH on a Mongo-db instance. I've seen you have Redis & Cassandra as storage-types in the code; is there an easy way for me to store in on mongo as well? 

Greets
Tb

**Comment by aastafiev** [comment]
Hi,

you can use mongodb in asynchronous submodule


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by blah-crusader** [comment]
Mm, yes I have been trying to do that, but have little experience with async in Python and have no success so far in transforming my code for the past few hours to link to MongoDB in an asynchronous way.. Any tips?

**Comment by aastafiev** [comment]
What was the problem?


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by blah-crusader** [comment]
I've made a small example that gives 2 RunTimeWarnings that LSH.query & LSH.fit were never awaited. Also, I don't see the AsyncMinHashLSH object being created on the MongoDB instance & don't understand how to obtain query results in a similar fashion as the original MinHashLSH.query() provides.  Any thoughts? Note that the mongodb settings are just dummy here of course :) Thanks a lot for any advice

`from datasketch import MinHash
from datasketch.experimental.aio.lsh import  AsyncMinHashLSH


class LSH:

	def __init__(self, num_perm, threshold):
		self.num_perm = num_perm
		self.threshold = threshold
		self._storage = {'type': 'aiomongo',
						 'mongo': {'host': '1.1.1.1', 'port': 11111, 'db': 'meh',
								   'username': 'blah', 'password': 'meh'}}
		self.lsh = AsyncMinHashLSH()

	async def fit(self):
		self.lsh = await AsyncMinHashLSH(storage_config=self._storage, threshold=self.threshold,
								   		num_perm=self.num_perm)
		minhash = MinHash(num_perm=self.num_perm)
		minhash.update('blah'.encode('utf-8'))
		await self.lsh.insert("1", minhash)
		self.lsh.close()

	async def query(self, string):
		minhash = MinHash(num_perm=self.num_perm)
		minhash.update(string.encode('utf-8'))
		idxs = await self.lsh.query(minhash)
		return [int(idx) for idx in idxs]


def main():
	lshasher = LSH(num_perm=40, threshold=0.95)
	lshasher.fit()
	print(lshasher.query('mehmeh'))


if __name__ == '__main__':
	main()
`

**Comment by aastafiev** [comment]
Hope this will help.

`
from datasketch.experimental.aio.lsh import  AsyncMinHashLSH
import asyncio


class LSH:

    def __init__(self, num_perm, threshold):
        self.num_perm = num_perm
        self.threshold = threshold
        self._storage = {
                'type': 'aiomongo',
                'mongo': {
                    'host': 'localhost',
                    'port': 27017,
                    'db': 'db',
                },
        }
        self.lsh = None

    async def fit(self):
        self.lsh = await AsyncMinHashLSH(
                storage_config=self._storage,
                threshold=self.threshold,
                num_perm=self.num_perm
        )
        minhash = MinHash(num_perm=self.num_perm)
        minhash.update('blah'.encode('utf-8'))
        await self.lsh.insert("1", minhash)

    async def query(self, string):
        minhash = MinHash(num_perm=self.num_perm)
        minhash.update(string.encode("utf-8"))
        return await self.lsh.query(minhash)

    async def close(self):
        await self.lsh.close()


async def main():
    lshasher = LSH(num_perm=40, threshold=0.95)
    await lshasher.fit()
    print(await lshasher.query("blah"))
    await lshasher.close()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
`

P.S.: To write effective code you should consider drill down to asyncio framework. Moreover, I suggest prevent constructing such wrapper class. All you need is (love :)) already implemented in AsyncMinHashLSH.

**Comment by blah-crusader** [comment]
Hi, thanks for the reply, this seems very similar to what I have been doing last night, I will compare! I was realizing this yesterday evening  and managed to get something to run after reading a blog on async/await :) You are fully right with the effective code part (and also the all you need is love part), but sometimes you just try and copy paste stuff and get it to work without using brain :) Thanks a lot for the help..

**Comment by aastafiev** [comment]
No problem :)

Will help with pleasure 


---------------------
Sincerely yours,
Aleksey Astafiev
