### ISSUE TITLE
Querying AsyncMinHashLSH returns [] for inserted keys

### ISSUE THREAD

**Issue by blah-crusader** [ekzhu/datasketch#118]
Hi guys, 

I'm having an issue with querying an AsyncMinHashLSH object persisted on MongoDB. I've replicated my issue using the example in the documentation. Similarly as in your example, I first create some random data, calculate minhashes & then use an insertion session to bulk-load them onto MongoDB. When I try to open a query after that, however, I'm getting "[]" as a result for querying one of the just inserted keys.. Is this normal? My code is below, where  the _storage object is cleared, so you'd need to fill it in order to make the code run ..  

```
from datasketch.experimental.aio.lsh import AsyncMinHashLSH
from datasketch import MinHash
from itertools import islice
from itertools import chain
import string
import random
import asyncio

_storage = {}

def chunk(it, size):
    it = iter(it)
    return iter(lambda: tuple(islice(it, size)), ())

async def func():
    async with AsyncMinHashLSH(storage_config=_storage, threshold=0.5, num_perm=16) as lsh:
        async with lsh.insertion_session(batch_size=1000) as session:
            fs = (session.insert(key, minhash, check_duplication=False) for key, minhash in data)
        await asyncio.gather(*fs)

async def query(mh):
    async with AsyncMinHashLSH(storage_config=_storage, threshold=0.5, num_perm=16) as lsh:
        return await lsh.query(mh)


if __name__ == "__main__":
    _chunked_str = chunk((random.choice(string.ascii_lowercase) for _ in range(1000)), 4)
    seq = frozenset(chain((''.join(s) for s in _chunked_str),
                          ('aahhb', 'aahh', 'aahhc', 'aac', 'kld', 'bhg', 'kkd', 'yow', 'ppi', 'eer')))
    objs = [MinHash(16) for _ in range(len(seq))]
    for e, obj in zip(seq, objs):
        for i in e:
            obj.update(i.encode('utf-8'))
    data = [(e, m) for e, m in zip(seq, objs)]

    asyncio.run(func())
    print(asyncio.run(query(mh=data[0][1])))
```

Any help would be greatly appreciated!
Greetings, 
Thibault

**Comment by aastafiev** [comment]
Hi.

Running ```func()``` for the first time you inserting into ```AsyncMinHashLSH``` object data and close it (```async with ...```). The second run - ```query()``` - you again creating a new object ```AsyncMinHashLSH``` and querying into empty object and than close it in ```async with ...```

**Comment by blah-crusader** [comment]
Hey, thanks for the reply. I see your point, I thought the storage_config made sure I am considering the same stored data which would allow me to query it or something :) I'm a bit puzzled then on how to use the stored data in the MongoDB once I've closed AsyncMinHashLSH. Is it correct that I should write MongoDB queries for that instead of using the library? Probably yes, then my question was a bit stupid :)

**Comment by aastafiev** [comment]
Well...
You have two options:
1. In one process create AsyncMinHashLSH once. Insert all data you need. Query all you need. Than close.
2. Create in one process AsyncMinHashLSH.  Insert all data you need. Pickle object. Close it. Than create other process. Unpickle saved object. Query all you need. Close it.

You don't need to access directly LSH index in MongoDB. It's a part of AsyncMinHashLSH index object data structure.

**Comment by blah-crusader** [comment]
Aha! The pickle part! Muchos Thankos!
