### ISSUE TITLE
MinHashLSHForest on MongoDB

### ISSUE THREAD

**Issue by blah-crusader** [ekzhu/datasketch#119]
Hi there,

For storing MinHashLSH on MongoDB, I've been able to use AsyncMinHashLSH; but it seems MinHashLSHForest is much better for my use case. I'd like to find a way to store this one on MongoDB as well. Therefore, I was wondering if anyone has worked on something similar in the past or whether you have any references that could help me implement it myself? 

Thanks a lot for the help!

**Comment by ekzhu** [comment]
Currently we don't have external memory storage layer for LSH Forest because it is not using hash tables. 

An ideal storage back-end for LSH Forest should support a sorted list and fast iteration over it.

**Comment by blah-crusader** [comment]
Alright, thanks for the tip!

**Comment by twoodhouse** [comment]
@blah-crusader, or @ekzhu, does anyone have any additional recommendations or examples on persisting the LSH Forest?

**Comment by sigmod2021p493** [comment]
> 
> 
> @blah-crusader, or @ekzhu, does anyone have any additional recommendations or examples on persisting the LSH Forest?

Currently no. I think it depends on whether you want to persist the forest as a backup file (use `pickle.dump`) or an persistent index supporting random access (not supported).
