### ISSUE TITLE
MinHash LSH for document clustering

### ISSUE THREAD

**Issue by apaullier** [ekzhu/datasketch#120]
Hello guys, I was wondering if MinHash LSH can be used for document clustering. Given a corpus of N documents is it possible to obtain somehow cluster labels? 

So far I have seen that given a certain document I can retrieve with a query the documents which their Jaccard similarity is over a certain threshold. I can do this for every document and get a binary symmetric matrix (documents by documents size) which contains 1s if two documents are similar 0s if dissimilar. The problem about this is that similarity is not transitive (i.e: a is similar to b, b is similar to c, a is not necessarily similar to c). 

One other issue i have been encountering is how to create m1,...,mN MinHash() functions without doing it manually, as I have thousands of documents.

Thank you in advance

**Comment by ekzhu** [comment]
This thread may be helpful: https://github.com/ekzhu/datasketch/issues/76

> In MinHashLSH, if you are using the default storage config option(i.e., dict), the hashtables would be just a list of a subclass of collection.defaultdict types. So for each hash table, you could just iterate over the keys and get the bucket as a list, and for each list, you can generate all pairs for that bucket. If you do this for all hash tables, and deduplicate the results, you can get all pairs produced by the MinHashLSH.

**Comment by apaullier** [comment]
Thank you very much! In case someone wants to implement something similar this is what I did:

1) Create a function that outputs an MinHashLSH model
2) Create a function that outputs predictions given the previously obtained model. This output is a list of lists that for each document ID outputs all document IDs which are over the required similarity threshold.
3) For each prediction list generate all possible pairs of IDs using ```itertools.combinations(i, 2) ```, where i is the predicted ID list for a certain document.
4) Create connected nodes (which will be our clusters) using: 
```
G = nx.Graph() # build node graph
G.add_edges_from(flat_list) 
```
5) Get every cluster's IDs using:
```
clusters = list(nx.connected_components(G))
```
6) Loop through the clusters ID and assign each element a unique cluster label.

**Disclaimer:** similarity is not transitive (i.e: if A is similar to B, B is similar to C, A and C are not necessarily similar). However, the higher the similarity threshold set on the LSH model the closer you will be to this assumption.
