### ISSUE TITLE
Allow aioMongo config to set DSN and Collection Name directly

### ISSUE THREAD

**Issue by ekevoo** [ekzhu/datasketch#123]
I use [Mongo Atlas](https://www.mongodb.com/cloud/atlas), and, as such, my database connection string starts with `mongodb+srv://`. None of the currently supported options in [experimental/aio/storage.py](https://github.com/ekzhu/datasketch/blob/master/datasketch/experimental/aio/storage.py#L134-L139) currently support that.

Additionally, I noticed that the collection name is a very opaque four-character prefix and a random string. I need to be able to modify that as well, if only at least the prefix.

I'm open to creating a Pull-Request to fix that, and I might just start doing this tomorrow, but I'd like to open the issue first.

**Comment by ekzhu** [comment]
@ekevoo Thank you for your contribution! I am closing this issue now.
