### ISSUE TITLE
Little-endian vs big-endian,  The problem of reappearance in Java platform ？

### ISSUE THREAD

**Issue by casolxia** [ekzhu/datasketch#126]
hi,
in  minhash.py
hashfunc=sha1_hash32,
struct.unpack('<I', hashlib.sha1(data).digest()[:4])[0],
I can  reappearance  this  "hashlib.sha1(data).digest()[:4]",
but i don't konw how reappearance    "  struct.unpack('<I'   ",Little-endian
in java platform.

**Comment by ekzhu** [comment]
What do you mean by "reappearance"?

**Comment by casolxia** [comment]
> What do you mean by "reappearance"?
like that:
The same algorithm , was  implemented in different programming languages

**Comment by casolxia** [comment]
就是在以小端解析： struct.unpack('<I' "，
在java上如何实现这种小端解析，复现python的这个struct.unpack，暂时还没找到好的实现方式

**Comment by casolxia** [comment]
ok, use javolution can implent it,http://javolution.org/apidocs/javolution/io/Struct.html

**Comment by ekzhu** [comment]
Cool. Good that you found the solution :)
