### ISSUE TITLE
Logic Issue for Optimal LSH Parameters

### ISSUE THREAD

**Issue by EdwardJRoss** [ekzhu/datasketch#129]
Thanks for building and maintaining this library; I've found MinHash really useful.

I think the `_false_positive_probability` and `_false_negative_probability` functions used to optimise the LSH parameters are wrong.

For example [`_false_positive_probability`](https://github.com/ekzhu/datasketch/blob/8274ebec58f04fb96347fc4fa568f1913c25ae38/datasketch/lsh.py#L30) returns the integral of `_probability` from 0 to `threshold`. Here `_probability` gives the probability that a pair with Jaccard similarity `s` will be returned by the function.

If `_probability` was somehow constant, say 0.5, then `_false_positive_probability` which is the probability a pair with Jaccard distance below the threshold will be returned should be 0.5. But the function will return `0.5 * threshold`.

I think this code might be trying to calculate the expectation value of false positives and false negatives (?) If you assume the similarities are uniformly distributed then you could do this by dividing by the size of the interval:
e.g.

```
def _false_positive_probability(threshold, b, r):
    _probability = lambda s : 1 - (1 - s**float(r))**float(b)
    a, err = integrate(_probability, 0.0, threshold)
    return a / threshold

def _false_negative_probability(threshold, b, r):
    _probability = lambda s : 1 - (1 - (1 - s**float(r))**float(b))
    a, err = integrate(_probability, threshold, 1.0)
    return a / (1 - threshold)
```

But the assumption similarities are uniformly distributed is a very bad one; typically there will be very relatively few duplicates and lots of non-duplicates.
So it's actually not clear to me whether the suggestion above will perform better or worse than what's already in the library.

I notice [MMDS](http://infolab.stanford.edu/~ullman/mmds/ch3.pdf) they use the threshold as where the curve is steepest, approximately at `(1/b)**(1/r)` (where the probability is around `1 - exp(-1) ~ -.6`).

**Comment by ekzhu** [comment]
Thanks for the issue. The function `_false_positive_probability` and `_false_negative_probability` are not computing the probability density function over the domain of similarity, rather, they compute the accumulated probability of false positives and false negatives over a range of similarity (i.e., [0, threshold] and (threshold, 1]).

The probabilities here are all conditional on Jaccard similarity -- they are all likelihood. So we don't consider the prior distribution of Jaccard similarity in this calculation because we cannot make any assumption about user input.

**Comment by EdwardJRoss** [comment]
I don't understand on how they "accumulate the probability of false positives and false negatives". They calculate the average value of false positives/negatives over the range of similarity, multiplied by the width of the range. It doesn't make sense to me that these functions should be proportional to the width of the range. (The expression `1 - (1 - s**float(r))**float(b)` is the probability a pair with similarity `s` will pass through the filter, not a probability density to integrate over).

It makes sense to not make any assumption about user input; I'm trying to work out the intention of integrating over similarities.

On reflection though it seems to work well enough and in practice it's common to tune the threshold to an application so it may not make sense to change it anyway.
