### ISSUE TITLE
pairwise jaccard similarity for 200k paragraphs

### ISSUE THREAD

**Issue by SankBad** [ekzhu/datasketch#131]
Hi,

I want to calculate the pairwise Jaccard similarity for 200k paragraphs using MinHash function. if I used 2 for loops it's really expensive. is there any other method?

**Comment by ekzhu** [comment]
Check out MinHash LSH: you can index the MinHash of 200k paragraphs in an LSH index, and then query each one of them to find the highly similar pairs.

**Comment by SankBad** [comment]
Thanks for the suggestion.
I needed a pairwise Jaccard similarity matrix i.e. for all the possible pairs. I used spark to invoke parallel computing.
Thanks!
