### ISSUE TITLE
Query system for MinHash + Jaccard

### ISSUE THREAD

**Issue by ajosh0504** [ekzhu/datasketch#136]
Looks like there is a way to do `lsh.query(m1)` to get LSH neighbors. Is there a way to get a list of neighbors  of m1 based on estimated Jaccard i.e. the output of `m1.jaccard(m2)` where m2 is minhashes already in the database?

**Comment by ekzhu** [comment]
If I am understanding you correctly: you want the closet neighbors of `m1` in Jaccard similarity?

LSH returns neighbors that have Jaccard similarity higher than the given threshold (approximately). Once you get the results from LSH you can just rank the result in descending order by `m1.jaccard(m2)`.

**Comment by ajosh0504** [comment]
That works, thanks!
