### ISSUE TITLE
How To Remove some pair (key, minhash) from MinHashLSH?

### ISSUE THREAD

**Issue by tomorrow1pan** [ekzhu/datasketch#138]
Hello, Very appreciate this projects. Now I use "pickle" to persist MinHashLSH. With an insertion session, I insert a large number of MinHashes in sequence. The code like that:
```
with open("0929_lsh.pickle", "rb") as pk_file:
    lsh = pickle.load(pk_file)
with lsh.insertion_session() as session:
    for key, minhash in hash_list:
        session.insert(key, minhash)
```
Now I want to remove some pair (key, minhash) from MinHashLSH, What Can I do? 
Thanks a lot.
@ekzhu

**Comment by ekzhu** [comment]
Is [this](http://ekzhu.com/datasketch/documentation.html#datasketch.MinHashLSH.remove) what you are looking for?

**Comment by ekzhu** [comment]
@tomorrow1pan  does this solve your issue?

**Comment by tomorrow1pan** [comment]
Thanks a lot!
