### ISSUE TITLE
MinHashLSH query returns sets with Jaccard similarity less than the threshold

### ISSUE THREAD

**Issue by AhmedHlel** [ekzhu/datasketch#140]
Hello,

I set up the threshold as 0.6 for the MinHashLSH object.
But after calling query on a MinHash (let's call it 'X') , some elements of the returned list, have a jaccard similarity with 'X' less than 0.6. (it was 0.578125).

Thank you!

**Comment by ekzhu** [comment]
LSH index returns approximate results, so expect some error. You can apply a post-processing filter to remove the false positives.

**Comment by AhmedHlel** [comment]
Thank you!
