### ISSUE TITLE
AsyncMinhashLSH doesn't use index key with mongodb backend, and hence is very slow.

### ISSUE THREAD

**Issue by oisincar** [ekzhu/datasketch#146]
We'd struggled with AsyncMinhashLSH's query performance, eventually finding out it wasn't using the default collection index key ('_id'), and instead querying by it's 'key' field. (see: [here](https://github.com/ekzhu/datasketch/blob/05298e5f1767ad6f29f4f101e192bf01b528f77f/datasketch/experimental/aio/storage.py#L206) )

This can either be fixed by inserting into the collections with primary key '_id', or else creating indices on the 'key' field for all collections in the database.

For anyone looking for the quickfix solution, simply run:

`db.lsh_...._bucket_#.createIndex( { key: -1 } )`

on each of the buckets and key collections in the database. We found performance went from 11 seconds/ query to >1ms/ query pretty much instantly.

I believe this should be added to the documentation somewhere, or fixed in the code (although it'd break existing databases). I'd volunteer to do either!

**Comment by ekzhu** [comment]
@aastafiev 

Thanks for raising this important issue. Do you think using an additional index would increase storage cost by a lot? It seems to me that using the primary for the key field is more efficient.

**Comment by oisincar** [comment]
No problem! I'm afraid I don't know enough about these dbs to know how it'd affect things. Mongodb does at least populate the _id field when it's unused, which is pretty significant when there's only key/hash in the db already.

**Comment by aastafiev** [comment]
I agree indexing significantly increase performance, but, for my opinion, it’s better to control indexing outside package by DB admins. Would it help to mention this in documentation or you insist on including indexing in package?


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by ekzhu** [comment]
How about giving users the option to choose which field to use as the key in the storage config? E.g., 

```python
_storage = {'type': 'aiomongo', 'mongo': {
'host': 'localhost', 
'port': 27017, 
'db': 'lsh_test',
'key_field': '_id',
}}

```

**Comment by aastafiev** [comment]
﻿If user could set this option, why user couldn’t set indexes before using the package?
Basically, we use “key”, as filtering key and couldn’t use “_id”. So using it as index would help in performance. But it will significantly increase db size in case of large amounts of data.

I think the best way to make users life easier is to force index creation in package.
---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by oisincar** [comment]
Ah, as Aleksey said '_id' needs to be unique so we couldn't use it. I guess then the only solution left is to simply create an index on the 'key' field when the collections are created.

I don't think you ever realistically want no index, even if the db would be larger. A single query on ~5 mil docs without the index takes over 10 minutes, while the db is still 5-6GBs (i.e. pretty small in modern terms).

**Comment by ekzhu** [comment]
Sure. Let's create index for the users. @oisincar do you want to take stab at this and make a pull request?

**Comment by oisincar** [comment]
Apologies I missed this. Yup, I'd be happy to.
