### ISSUE TITLE
Top-k with MinHash LSH Ensemble?

### ISSUE THREAD

**Issue by LSparkzwz** [ekzhu/datasketch#150]
Hello, I've seen that MinHash LSH Forest is a variation of MinHash LSH for top-k queries instead of threshold ones.
Is it possible to do top-k queries with MinHash LSH Ensemble?

**Comment by ekzhu** [comment]
So far LSH Ensemble does not support top-k query natively. However you can always retrieve by threshold first and do a sort-by on the intermediate result, then take the top-k.
