### ISSUE TITLE
Why is the size of the hyperloglog sketch the same no matter the parameter?

### ISSUE THREAD

**Issue by lesshaste** [ekzhu/datasketch#155]
Whatever I set the parameter p to, the size of the sketch doesn't change. I check it with `sys.getsizeof(h)`. Shouldn't the size increase with `p`?

**Comment by ekzhu** [comment]
The size should increase with p. Maybe check the [documentation](https://docs.python.org/3/library/sys.html#sys.getsizeof) of `sys.getsizeof` ?
