### ISSUE TITLE
Support for MySQL as LSH storage

### ISSUE THREAD

**Issue by surkova** [ekzhu/datasketch#158]
There's a Go [implementation](https://github.com/ekzhu/go-sql-lsh) for LSH storage for Postgres and SQLite, though there's none for MySQL. Neither of relational databases is supported directly in this library, I wonder why?

**Comment by ekzhu** [comment]
Memory is often large enough for most usage scenarios of LSH. Plus in-memory data structure is better optimized for querying and updates. If you want persistence, just use `pickle.dump` and `pickle.load`. The LSH is not your primary data store just a retrieval index, so it doesn't hurt to rebuild it from scratch -- it is also fast.

I am not sure what's the usage scenario for SQL-based LSH storage though.

**Comment by ekzhu** [comment]
Cool scenario! 

Do you think having multiple indexes may help with the storage issue with a single index? You can parallelize query over multiple indexes. Of course there will be duplicate across different indexes but you can always dedup in post-processing. Also, once in a while you can compact your indexes by inserting all the entries in to one.

I think a universal serialization method would be great for persistent storage: Stores the LSH index in a binary format, and deserailize into various storage engines such as memory, Redis, etc.. We may be able to use a well-supported binary format such as [Numpy's](https://github.com/numpy/numpy/blob/main/doc/neps/nep-0001-npy-format.rst).

**Comment by surkova** [comment]
We are looking into horizontal scaling of Redis instances with help of a proxy, but for this we would need some way to route how the new keys are being inserted. 

Do you think you might be adding LSH serialization to the library in the near future?

**Comment by ekzhu** [comment]
> Do you think you might be adding LSH serialization to the library in the near future?

Sorry for the late late reply. I don't have plan to add new features in the near future. But if you submit a pull request I would be happy to review it.
