### ISSUE TITLE
how to pass username and password to cassandra storage config?

### ISSUE THREAD

**Issue by FrancisKong** [ekzhu/datasketch#161]
I didn't see any information about auth configuration of Cassandra

**Comment by ekzhu** [comment]
https://github.com/ekzhu/datasketch/blob/5a15b1752f0ae42cd396882ebd120b0d1e1dcee0/datasketch/storage.py#L670

I think you can pass the credentials as part of the config? The config is passed directly into the Cassandra client.

**Comment by FrancisKong** [comment]
Thanks for your answer. For anyone who have the same problem:
```python
    lsh = MinHashLSH(threshold=0.8, num_perm=128, storage_config={
        'type': 'cassandra',
        'cassandra': {
            'auth': {
                'username': 'your-username',
                'password': 'your-password'
            }
        }
    })
```

> https://github.com/ekzhu/datasketch/blob/5a15b1752f0ae42cd396882ebd120b0d1e1dcee0/datasketch/storage.py#L670
> 
> I think you can pass the credentials as part of the config? The config is passed directly into the Cassandra client.

**Comment by pavelnemirovsky** [comment]
@FrancisKong @ekzhu , are you certain it's functioning? Based on the code, it shouldn't be. In my case, it's not working due to the absence of _auth_provider.
<img width="814" alt="image" src="https://github.com/ekzhu/datasketch/assets/19474975/8f9fc515-923f-4617-ba85-9ee2a7ab5ad8">

**Comment by pavelnemirovsky** [comment]
I'll submit a PR that adds support for both auth and SSL transport. This should also resolve the issue found at https://github.com/ekzhu/datasketch/issues/176.

**Comment by ekzhu** [comment]
Thanks! @pavelnemirovsky
