### ISSUE TITLE
Different code in the tar.gz and whl file

### ISSUE THREAD

**Issue by mal-mel** [ekzhu/datasketch#170]
Hello, i try to use your new feature (connect to the mongo by uri), but when installing version 1.5.4, there is no functionality for working with mongo uri.

In PyPi, the tar.gz file and the whl file contain different code.

Specifically, the storage.py file in experimental dir is different :(

https://pypi.org/project/datasketch/1.5.4/#files

**Comment by WhattaSkilL** [comment]
up

**Comment by ekzhu** [comment]
Thanks for the issue. The problem should be fixed in 1.5.6.
