### ISSUE TITLE
def jaccard 's denominator is self not [self union other] .

### ISSUE THREAD

**Issue by xiaocaicode** [ekzhu/datasketch#213]
Hello，I'm new to MinHash, I doubt the function to caculate jaccard  , 
according to docs: https://en.wikipedia.org/wiki/Jaccard_index
jaccard = |A intersection B | /  |A union B |  , but your code here the denominator is A not [A union B] .
Please let me know if my thoughts is wrong or not .

code is here : 
https://github.com/ekzhu/datasketch/blob/master/datasketch/minhash.py
def jaccard(self, other):
        '''Estimate the `Jaccard similarity`_ (resemblance) between the sets
        represented by this MinHash and the other.

        Args:
            other (datasketch.MinHash): The other MinHash.

        Returns:
            float: The Jaccard similarity, which is between 0.0 and 1.0.
        '''
        if other.seed != self.seed:
            raise ValueError("Cannot compute Jaccard given MinHash with\
                    different seeds")
        if len(self) != len(other):
            raise ValueError("Cannot compute Jaccard given MinHash with\
                    different numbers of permutation functions")
        **return float(np.count_nonzero(self.hashvalues==other.hashvalues)) /\
                float(len(self))**

**Comment by ekzhu** [comment]
You definition of Jaccard is correct for sets. However, MinHash is not a set. The operator for estimating Jaccard with MinHash is the unbiased estimate of the probability of hash collision.  https://en.wikipedia.org/wiki/MinHash

**Comment by xiaocaicode** [comment]
Thank you so much for your quick reply! 
I get it , the denominator must be the num of  hash_function_count= number of matrix rows after dimension reduction by using minhash.
Thank you again!
