### ISSUE TITLE
Jaccard calculation

### ISSUE THREAD

**Issue by titusz** [ekzhu/datasketch#29]
The MinHash.jaccard method calculates the size of the intersection divided by **number of hash values**. Shouldn't that be the size of intersection divided by the **size of the union**? See: https://en.wikipedia.org/wiki/Jaccard_index

**Comment by ekzhu** [comment]
The first "intersection" you mentioned is not the intersection of set values. It is simply the number of matching hash values between two Minhash. The probability of a single pair of hash values being equal is the same as the Jaccard similarity of two sets.

See Chapter 3 of Mining of Massive Datasets (http://infolab.stanford.edu/~ullman/mmds/ch3.pdf)

Yes. To compute the exact Jaccard similarity, you take the intersection size and divide by the union size.
