### ISSUE TITLE
Implement __hash__ method for LeanMinHash class

### ISSUE THREAD

**Issue by arisudesu** [ekzhu/datasketch#31]
Hello,

as the lean minhash objects are immutable, can you implement special method `__hash__` on them? That would allow to use them easily in collections that require hashable objects.

**Comment by ekzhu** [comment]
I feel this is a good idea. Any idea for a good implementation of `__hash__()`? My immediate idea is to simply use `hash()` on a tuple of all the hash values, prepended by the random seed.

**Comment by arisudesu** [comment]
Should be enough, I think.
