### ISSUE TITLE
Feature request: SuperMinHash

### ISSUE THREAD

**Issue by vmarkovtsev** [ekzhu/datasketch#32]
I've recently found out about [SuperMinHash](https://arxiv.org/pdf/1706.05698.pdf). Are there any plans to provide a reference implementation here? I would volunteer to add it if there are no official plans.

**Comment by ekzhu** [comment]
I don't have any plan right now. Sounds good :+1:  some benchmark experiments would be awesome.

**Comment by ekzhu** [comment]
Close due to inactivity.
