### ISSUE TITLE
Source distribution not available in pypi

### ISSUE THREAD

**Issue by arisudesu** [ekzhu/datasketch#33]
This might seem an odd issue, though, I am unable to install the library in the environment, where usage of wheels is prohibited (i. e. all the python packages are installed from source). The pip says there is no available source distributions except for version 0.2.6: https://gist.github.com/anonymous/0643b6edf0def8d8f300dbe0b5f0b976. Other libraries usually upload sources, and are installed ok. Can you please upload source distribution to pypi?

**Comment by ekzhu** [comment]
Thanks for the reminder. Here you go: https://pypi.org/project/datasketch/1.2.3/#files. I will add source distribution in future versions.
