### ISSUE TITLE
how to change IP in minlsh

### ISSUE THREAD

**Issue by rickyqiao** [ekzhu/datasketch#39]
Hey,nice to meet you!
In your code, there is some code to create lsh like:
lsh = MinHashLSH(threshold=0.91, num_perm=128, storage_config={
           'type': 'redis',
            'redis': {'host': '10.8.35.7', 'port': 6379, 'db': 9}, 'name': 'abcdefghij'}, prepickle=True) 

If such lsh had create,and some data had already add into it, how can I change this IP?

**Comment by ekzhu** [comment]
Currently there is no public method to do this. I think you would have to recreate the LSH with the new configuration. 

Alternatively you can work around this by modifying the storage of the LSH object manually.
