### ISSUE TITLE
what is wrong with this 'Error 111 connecting to localhost:6379. Connection refused.'

### ISSUE THREAD

**Issue by rickyqiao** [ekzhu/datasketch#40]
When I add more data into lsh, 'Error 111 connecting to localhost:6379. Connection refused',this error was created, what is the problem and how can I slove it?Thank you so much

**Comment by duhaime** [comment]
@rickyqiao 6379 is the default port for Redis--it looks like your client can't connect with the Redis server. Can you try starting/restarting the Redis server on your machine?
