### ISSUE TITLE
How to speedup indexing?

### ISSUE THREAD

**Issue by alexeyev** [ekzhu/datasketch#41]
Hi, thanks for the amazing package!

Are there any ways to speedup the indexing for similarity search for hundreds of millions MinHashes?
I do it like that 

```python
        lsh = MinHashLSH(threshold=THRESHOLD, num_perm=NUM_PERM)

        for i, row in enumerate(spamreader):
            i += 1
            if i % 50000 == 0:
                with lsh.insertion_session() as session:
                    for key, minhash in collector:
                        session.insert(key, minhash)
                collector.clear()
                print("Inserted ", i)

            id = row[0]
            items = row[1].strip().split(",")  # typically a short list

            m = MinHash(num_perm=num_perm)

            for item in items:
                m.update(item.encode("utf-8"))

            collector.append((id, m))
```

...and it takes quite a while, which doesn't allow me to carry out my experiments.

```python
NUM_PERM = 128
THRESHOLD = 0.6
```

**Comment by ekzhu** [comment]
Hi, I think when you have hundreds of millions of MinHashes, you may want to consider using redis as the storage layer https://ekzhu.github.io/datasketch/lsh.html#minhash-lsh-at-scale.

Another thing you can do:
1. Create all the MinHashes first, serializing them on-the-fly into some storage (e.g. file or database) using the [Lean MinHash](https://ekzhu.github.io/datasketch/documentation.html#lean-minhash) class.
2. Create the LSH by reading MinHash directly from your storage.

This helps you to separate indexing into 2 stages, and you can benefit from it when you modify your LSH configurations without having to regenerate MinHashes.

**Comment by alexeyev** [comment]
Cool, thanks for the advice!
