### ISSUE TITLE
Feature request: more distance measures

### ISSUE THREAD

**Issue by pandasMX** [ekzhu/datasketch#43]
Hi, I found that in your implementation, the distance measures are only jaccard distance and weighted jaccard distance. 

But for the weighted jaccard distance, the vectors used for comparison should not be negative. But in some cases it may have negative values in the vectors (e.g. after compressing a very high dimension vector using PSA). 

Do you have any plan to add more distance measures like euclidean and cosine distance? Thanks.

**Comment by ekzhu** [comment]
The weighted minhash signature only supports jaccard similarity. Are you referring to [simhash](https://github.com/leonsim/simhash) for cosine similarity or [p-stable distribution LSH](https://github.com/ekzhu/lsh) for euclidean distance?

**Comment by Shellcat-Zero** [comment]
A key failing here is that the other implementations do not appear to allow for asynchronous queries.  A possible candidate though may be [NearPy](https://github.com/pixelogik/NearPy).
