### ISSUE TITLE
Feature Request / Question: Non-text unweighted minhash

### ISSUE THREAD

**Issue by daenuprobst** [ekzhu/datasketch#49]
Is it possible to hash data encoded as binary "array strings" (not sure if this makes sense in python, in C I'd encode it using integer or maybe boolean arrays)? For example:
```python
a = '1000101001'
b = '1000100101'
```
Now I would like to get the jaccard distance between those two data points. How would I minhash those values? Would this need a change in the implementation?

**Comment by ekzhu** [comment]
No change is needed. MinHash treats all inputs as raw bytes:

```python
minhash.update("1000101001".encode('utf-8'))
```
