### ISSUE TITLE
how to restore minhashes from MinHashLSH with redis backend?

### ISSUE THREAD

**Issue by bung87** [ekzhu/datasketch#51]
I what to find duplicates,so I need pop a hash then compare left hashes.

or should I make a copy of original data to redis?
or just not use the redis storge wait the dataset feed up then use MinHashLSH

**Comment by ae-foster** [comment]
Hi @bung87 do you think you could give a bit more detail about your question? What's your exact use case?

**Comment by bung87** [comment]
Question is :
here's two type of data:

**articles**  may store to redis  
**create_lsh** may use redis backed  

Should I store both articles and lsh's minhashes to redis?

in production also I need store key of each articles.

things am trying to do below;

```python
def duplicates(content, debug=False):
 
    if type(content) == list:
        articles = content
    else:
        articles = split_articles(content)
    minhashs = create_minhashs(articles, debug=debug)
    result = defaultdict(list)

    matched = []
    lsh = create_lsh(minhashs, threshold=0.75, num_perm=128, debug=debug)
    while minhashs:
        cur_index = len(minhashs) - 1
        cur = minhashs.pop()
        if not cur or cur_index in matched:
            continue
        # debug and print("creat lsh done %s" % cur_index)
        r = lsh.query(cur)
        if r:
            for idx in r:
                if idx != cur_index and idx not in matched and idx not in result:
                    result[cur_index].append(idx)
                    matched.append(idx)
    return result
```

**Comment by ae-foster** [comment]
@bung87 I'm still a bit unsure what your objective is. In general though, don't use the Redis backend unless you need to. If you can solve your problem within a Python process that will be the way to go!

**Comment by bung87** [comment]
hmm ..actually I just want make ** only one copy of data(keys and hashes)**,since datasketch just provide **query** interface,for finding duplicates,I must first make a minhash which needs the text as input.so in this case I must feed lsh with minhashes,and also store text dataset for each **query**,

what I need is this project does, and it does just make one copy of data.
https://github.com/mattilyra/LSH/blob/master/examples/Introduction.ipynb

in production that may not be a problem (in mine case). I just want make sure as if there is a clear way to achieve this.

thank you!

**Comment by duhaime** [comment]
@bung87 I for one am still not clear what you wish to accomplish. What makes you think multiple copies of data are being stored? What data exactly is being stored multiple times and where is it being stored?

**Comment by bung87** [comment]
I think it just needs **keys and minhashes** to find duplicates,but for now I also needs store text for create Minhash as query function requires.

**Comment by bung87** [comment]
thanks, I do exactly what you say,I put mine code above there and it works,here I open this issue just make sure I am not missing a simple clean way.
