### ISSUE TITLE
MinHash LSH Forest Accuracy

### ISSUE THREAD

**Issue by ronentk** [ekzhu/datasketch#52]
Hey,
I see this has been raised already in #42 , but even on what seems a very simple [example](https://colab.research.google.com/drive/1Qs4UPzX_d07qH5I3QqHiYJj5qoVWJmJZ), I'm getting some odd behavior using the MinHash LSH Forest.

I'm trying to do simple approximate string matching to collect citation data, and as you can see in the example, for even just 10 data-points, top-k performance deviates from the directly estimated Jaccard similarity.

Am I missing something maybe?
Thanks

**Comment by duhaime** [comment]
@ronentk One thing I've found when working with minhashing strings is that it's often helpful not to minhash at the token level but instead to minhash at the character trigram level. If you check out some of the literature on plagiarism detection you'll see that many of the papers use this technique. The "Mining of Massive Datasets" text (a great read if you haven't checked it out) also discusses this technique briefly.

In the case of your code, this would look like:

```
from datasketch import MinHash, MinHashLSH, MinHashLSHForest
from nltk import ngrams

NUM_PERMS = 256

# get hash for given string
def get_str_lsh(norm_title, num_perms=NUM_PERMS):
  mh = MinHash(num_perm=num_perms)
  for w in set(norm_title.split()):
    for ngram in ngrams(w, 3):
      mh.update(''.join(ngram).encode('utf8'))
  return mh

search_q = 'adam a method for stochastic optimization arxiv preprint arxiv phone'

# the index of the candidate we think is most likely
our_candidate_idx = 0

# our candidate along with some other titles
titles = ['adam a method for stochastic optimization in iclr',
          'steganographic generative adversarial networks arxiv preprint arxiv',
 'multiple object tracking a literature review arxiv preprint arxiv phone',
 'memory networks arxiv preprint arxiv phone',
 'stacked what-where auto-encoders arxiv preprint arxiv',
 'conditional generative adversarial nets arxiv preprint arxiv phone',
 'multi-scale context aggregation by dilated convolutions arxiv preprint arxiv',
 'least squares generative adversarial networks arxiv preprint',
 'task-driven visual saliency and attention-based visual question answering arxiv preprint arxiv',
 'wavenet a generative model for raw audio arxiv preprint arxiv']

forest = MinHashLSHForest(num_perm=NUM_PERMS)
lsh = MinHashLSH(threshold=0.5, num_perm=NUM_PERMS)

for i,title in enumerate(titles):
    forest.add(i, get_str_lsh(title))
    lsh.insert(i, get_str_lsh(title))

# index so all keys will be searchable
forest.index()

search_q_hash = get_str_lsh(search_q)

# find the top 5 matches
result = forest.query(search_q_hash, 5)
print(result)
print("Jaccard similarity of target query and our candidate: ", search_q_hash.jaccard(get_str_lsh(titles[our_candidate_idx])))
```
Output:

```
[0, 1, 2, 3, 6]
Jaccard similarity of target query and our candidate:  0.66015625
```

Does that seem more realistic?

**Comment by ronentk** [comment]
Yes, that is definitely an improvement, although using the tri-grams increases runtime as well. Thanks in any case for the good advice!
