### ISSUE TITLE
Check buckets of LSH MinHash

### ISSUE THREAD

**Issue by hsiaoma** [ekzhu/datasketch#55]
I want to have a rough clustering of input, that is, input sets that are similar to each other in terms of Jaccard coefficient should be grouped together. I think lsh may be able to accomplish such task since it hashes items similar to each other in the same bucket. I wonder if I can check which items are grouped together. I tried the following way but I do not think it is a good one.
`lsh.hashtables[6]._dict.values()`
Any help or suggestion is much appreaciated.

**Comment by ae-foster** [comment]
Here are a few thoughts for `MinHashLSH` instances.
1. A certain hash table, e.g. `hashtable = lsh.hashtables[6]`, is an instance of `UnorderedStorage` https://github.com/ekzhu/datasketch/blob/master/datasketch/storage.py#L160. The `_dict` attribute only exists when you're using a dict implementation. Wouldn't work with Redis. Best to use the methods available on `UnorderedStorage`.
2. **Replace your code**  with the following
```
hashtable = lsh.hashtables[6]
keys = list(hashtable.keys())
# View contents of a single bucket
bucket = hashtable.get(keys[0])
```
If you want an overview of bucket sizes, use
```
hashtable.itemcounts()
```
This is equivalent (but faster on Redis) to
```
[len(hashtable.get(k)) for k in hashtable.keys()]
```
3. There is also `hashtable.getmany(*keys)` but a quick perusal shows there might be a bug in the Redis implementation of that method for `UnorderedStorage`. (Will fix if people encounter in the wild).

**Comment by hsiaoma** [comment]
@ae-foster I am not using Redis but this is indeed a much better approach. Thanks a lot.
