### ISSUE TITLE
Elasticsearch storage

### ISSUE THREAD

**Issue by james4388** [ekzhu/datasketch#59]
I need to build image search database, using neural network to extract features and using weighted min hash, LSH to find similarity. How can I use elastic search for storing hash keys? I really new to this so please give me some guidance. May I submit pull request for es storage option?

**Comment by ekzhu** [comment]
Why not use the Redis storage backend?

**Comment by ekzhu** [comment]
@james4388, Elastic search may not be the best storage backend if fast lookup is what you desire. I suggest using Redis.
