### ISSUE TITLE
redis not persisting

### ISSUE THREAD

**Issue by nengine** [ekzhu/datasketch#60]
I was able to add MinHash into redis backed lsh.  But when try to reload lsh from another session all the keys/value I have added are not there anymore.  Is it possible that redis is not persisting key/value?  I was under impression that purpose of using redis backend is to be able to reuse from other processes.  Thanks.

```python
lsh = MinHashLSH(
 threshold=0.5, num_perm=128, storage_config={
    'type': 'redis',
    'base_name': 'unique_name_6ac4fg',
    'redis': {'host': 'localhost', 'port': 6379}
 })

doc = "Tales of Berseria "
mh = MinHash(num_perm=128)
for d in doc.split():
    mh.update(d.encode('utf8'))
lsh.insert("d1", mh)

lsh.__contains__("d1")

True
```
Now load lsh from another session and key/values are gone:

```python
lsh = MinHashLSH(
 threshold=0.5, num_perm=128, storage_config={
    'type': 'redis',
    'base_name': 'unique_name_6ac4fg',
    'redis': {'host': 'localhost', 'port': 6379}
 })

lsh.__contains__("d1")

False
```

**Comment by aastafiev** [comment]
There is a typo in documentation. The pull request for documentation is still waiting to merge. Try using "basename" instead of "base_name".

**Comment by nengine** [comment]
Ok Thanks a lot.

**Comment by ekzhu** [comment]
Doc fixed. Make sure also `basename` is a binary string: 

```python
b"unique_name_1231"
```
