### ISSUE TITLE
Store MinHashes for later queries

### ISSUE THREAD

**Issue by dharaghodasara** [ekzhu/datasketch#64]
Hi - I am using MinHashLSH for querying duplicate documents. This is exact flow of my use case.  

1. I have around 100K documents. 
2. when i open any document, it should show all other documents which are 90% match. 

For this, i am first calculating minhashes for each document and then adding it below LSH object. 

` MinHashLSH(num_perm=perms,threshold=0.9)
`
**Issue is** - this min hashes creation process itself takes around 470 sec. So i can't create it every time i query new document. 

So I am planning to store this LSH object in disk for future queries and update it may be once in a day/week.

Did any one try this before or know any better way to handle this type of use case? 

Thank You.

**Comment by aastafiev** [comment]
Hi,

You should use pickling. See https://ekzhu.github.io/datasketch/lsh.html#connecting-to-existing-minhash-lsh

**Comment by dharaghodasara** [comment]
Thanks @aastafiev for confirming.  That's what i thought. 

What do you recommend when should i update stored LSH? If i do daily/weekly then predictions will ignore newly created documents.

**Comment by aastafiev** [comment]
Well, it depends on your task.
I could tell how we've created pipeline:

1. getting MinHashes from new objects
2. indexing
3. distributing new indexes
4. quering
5. postprocessing

In this approach we don't have lag between new objects and already indexed.

**Comment by dharaghodasara** [comment]
Thanks @aastafiev for sharing your example. 

In my case, i need immediate response to query so i will probably update Minhashes hourly or on demand.

**Comment by dharaghodasara** [comment]
@aastafiev - One question i have is how should we handle deletion of document? 

Lets say i have created Minhashs and inserted into LSH obj, after an hour so someone has deleted that document then how should i remove that document from Minhashs?

**Comment by aastafiev** [comment]
For right deleting document from MinHashLSH index you should use "remove" method from MinHashLSH. See, documentation on API ([https://ekzhu.github.io/datasketch/documentation.html#minhash-lsh])
