### ISSUE TITLE
Make MinHash hashable

### ISSUE THREAD

**Issue by Dobatymo** [ekzhu/datasketch#65]
This class would be far easier to use if the objected were hashable. As this is a hashing class you would only have to expose the hash value as python interface with `__hash__`.

```
>>> from datasketch import MinHash
>>> m=MinHash()
>>> set([m])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'MinHash'
```

**Comment by ekzhu** [comment]
Hi, MinHash has an array of hash values, as well as the random permutation functions that used to generate the hash values. So, it is similar to `list`, which is not hashable.

**Comment by Dobatymo** [comment]
You are correct, I did not think about the implementation details.
However it would still be nice to have a hashable variant of `MinHash`, probably an immutable variant comparable to `FrozenSet`. That should be possible no?

**Comment by ekzhu** [comment]
An immutable variant is LeanMinHash: https://ekzhu.github.io/datasketch/documentation.html#datasketch.LeanMinHash. It has a `__hash__` function.
