### ISSUE TITLE
await AsyncMinHashLSH syntax error on python 3.6.5 anaconda

### ISSUE THREAD

**Issue by shaktisd** [ekzhu/datasketch#68]
Following example is not working with 1.2.7 , even after changing the import to
from datasketch.experimental.aio.lsh import AsyncMinHashLSH

I am getting error , invalid syntax for await. I am using python 3.6.5

lsh = await AsyncMinHashLSH(storage_config=_storage, threshold=0.5, num_perm=16)
                             ^
SyntaxError: invalid syntax

https://ekzhu.github.io/datasketch/lsh.html#minhash-lsh-at-scale

```
from datasketch.experimental.aio.lsh import AsyncMinHashLSH
from datasketch import MinHash, MinHashLSH


_storage = {'type': 'aioredis', 'redis': {'host': 'localhost', 'port': 6379}}

lsh = await AsyncMinHashLSH(storage_config=_storage, threshold=0.5, num_perm=16)
m1 = MinHash(16)
m1.update('a'.encode('utf8'))
m2 = MinHash(16)
m2.update('b'.encode('utf8'))
await lsh.insert('a', m1)
await lsh.insert('b', m2)
print(await lsh.query(m1))
print(await lsh.query(m2))
lsh.close()
```

**Comment by aastafiev** [comment]
Hello,

Try put the code from lsh into "async def func()".

I'll change the documentation later

**Comment by ekzhu** [comment]
Thank you @aastafiev
