### ISSUE TITLE
Accessing Minhash object

### ISSUE THREAD

**Issue by bioinfonm** [ekzhu/datasketch#7]
Hello,

  I stumbled across your code while looking up Minhashing. I was wondering if there is a way to access the Minhash object to retrieve the hashes? 

thanks,
ara

**Comment by ekzhu** [comment]
Hi, I think you can get the hash values by using
```
# mh is a minhash object
mh.hashvalues
```

**Comment by bioinfonm** [comment]
Perfect! Thank you.
