### ISSUE TITLE
is different hashobj will cause huge different profermence?

### ISSUE THREAD

**Issue by saselovejulie** [ekzhu/datasketch#71]
is different hashobj will cause huge different profermence?
like hashlib.sha1
or hashlib.md5
will effect CPU or result clusters?
thanks

**Comment by aastafiev** [comment]
You can have an experiment and share results with us

**Comment by ekzhu** [comment]
I am sure it would make some performance difference, but also keep in mind that a not-so-random hash function may decrease accuracy.

**Comment by ekzhu** [comment]
@saselovejulie If you are interested, take a look at this pull request #73.

**Comment by saselovejulie** [comment]
> @saselovejulie If you are interested, take a look at this pull request #73.

this really helpful, thanks
