### ISSUE TITLE
AsyncMinHashLSH threshold dynamic update

### ISSUE THREAD

**Issue by saselovejulie** [ekzhu/datasketch#72]
@ekzhu Hi, my data all insert into MongoDB with aiomongo.
is there anyway to using dynamic threhold after all data insert into Mongo?
thanks alot.

**Comment by ekzhu** [comment]
No, it is currently not possible to update the threshold after the index is created. Maybe you can create multiple indexes with different thresholds, or you can consider using LSH Forest (currently without mongo support).
