### ISSUE TITLE
MinHashLSH for spark

### ISSUE THREAD

**Issue by dharaghodasara** [ekzhu/datasketch#74]
Hi - I am planning to set up ML pipeline in Spark. I am using this library for similarity check. 

Is it possible to use this python package with pyspark ?

**Comment by ekzhu** [comment]
I think you can always import any Python package into pyspark code, although it is only for within each Spark executor/driver process.

**Comment by dharaghodasara** [comment]
Yes i understand i can use for standalone mode. But if i have multi node in spark cluster then how can i do distributed computation?

**Comment by ekzhu** [comment]
The answer to this question can be written as a book 📖 . MinHash has nice properties of supporting distributed processing, but this library does not include any distributed processing code.
