### ISSUE TITLE
redis has password? 

### ISSUE THREAD

**Issue by LULUFlora** [ekzhu/datasketch#77]
Hi, I want to use Redis to store, but the redis has password, how can I set the storage configuration?
I do it like this:

lsh = MinHashLSH(threshold=0.91, num_perm=128, storage_config={
'type': 'redis',
'redis': {'host': '10.8.35.7', 'port': 6379, 'password': *******}})

but it doesn't work.

**Comment by ekzhu** [comment]
Can you show us the error output? The configuration seems right

**Comment by ekzhu** [comment]
Closing this now due to no follow-up
