### ISSUE TITLE
percent match

### ISSUE THREAD

**Issue by vishaljhala** [ekzhu/datasketch#87]
I am using MinHashLSH. Library returns me matches above threshold. I want to sort them based on percent match. Is there a way to get percent match?

**Comment by ekzhu** [comment]
Can you define "percent match"

**Comment by vishaljhala** [comment]
Sure. It uses jaccard similarity. So lets say, if the intersection of words between 2 documents was 3 words and union of words is 5 then percent match = 3/5. I have specified a thershold of 0.6. So I know all results above 0.6 are being returned but within them, I want to know which one is the closest.

Hope this helps.

**Comment by ekzhu** [comment]
You get the keys back from the MinHashLSH. If you can also recover the MinHash sketches, you can compute the similarities using `jaccard()` method and then rank the result using the similarities.
