### ISSUE TITLE
Check duplicates with redis backend doesn't prepickle keys for MinhashLSH insert 

### ISSUE THREAD

**Issue by mboyanov** [ekzhu/datasketch#88]
Checking for duplicates when using the redis backend is inconsistent, because the **key** is not prepicled before the check. The prepickling happens afterwards. E.g. see below:
```
        if check_duplication and key in self.keys:
            raise ValueError("The given key already exists")
        Hs = [self._H(minhash.hashvalues[start:end])
              for start, end in self.hashranges]
        if self.prepickle:
            key = pickle.dumps(key)
```
Reference: https://github.com/ekzhu/datasketch/blob/b3e4129987890a2beb04f2c0b6dc618ae35f2e14/datasketch/lsh.py#L163

**Comment by ekzhu** [comment]
Thanks for pointing this out!
