### ISSUE TITLE
Unexpected/Incorrect Recommendation by MinHash LSH Forest.

### ISSUE THREAD

**Issue by akashmahagaonkar** [ekzhu/datasketch#89]
We have implemented Locality Sensitive Hashing based recommendation system using the Datasketch MinHash LSH Forest.

We are facing problem with the Jaccard Similarity Score predicted by the Datasketch MinHash LSH Forest.

For Example,
Suppose there are 3 sentences,
	Sentence A :  Query Text
	Sentence B :   Closest Match
	Sentence C : Predicted Match

J_AB = 0.38			J_MinHash_AB = 0.39
J_AC = 0.2			J_MinHash_AC = 0.2

J_AB : Actual Jaccard Similarity between Sentence A and Sentence B
J_MinHash_AB: Jaccard Similarity between Sentence A and Sentence B calculated by the MinHash.

We have two questions, 
1. Why the Datasketch MinHash LSH Forest is suggesting Sentence C as closest neighbor of Sentence A instead of Sentence B?

2. Given that MinHash LSH Forest will yield multiple Jaccard Similarities i.e.  J_MinHash_AB, J_MinHash_AC, J_MinHash_AD, …………, J_MinHash_AN can one access all of them?

**Comment by ekzhu** [comment]
The LSH Forest is an approximate index, so it doesn't guarantee ranked results. Also, LSH Forest does not compute Jaccard similarities. I would suggest you compute the similarities using MinHash (or exactly) after retrieving the keys from the LSH Forest index.
