### ISSUE TITLE
API or Interface

### ISSUE THREAD

**Issue by rojas70** [ekzhu/datasketch#9]
Would it be possible to include in the documentation the methods for each of the modules in dataSketch and how they are called?

**Comment by ekzhu** [comment]
Thanks for the suggestion. I am thinking about auto-generate documentation from the method and class comment in the code. Do you have any suggestion in what tool to use?

**Comment by straygar** [comment]
Try looking into pydoc. It's very easy to use and for a project of this size should suffice. Use docstrings to document the contents of your modules and use pydoc to generate the documentation.

Another alternative is Sphinx, which is a lot more robust, customisable and has a very active community, but will definitely take longer to apply.

**Comment by rojas70** [comment]
Thanks!

---------------------------------------------------
Dr. Juan Rojas
GDUT Associate Research Professor
School of Mechatronics (Electro-Mechanical Eng)
GuangDong University of Technology
*http:// <http://ss.sysu.edu.cn/~Rojas>www.juanrojas.net
<http://www.juanrojas.net>*

**Comment by ekzhu** [comment]
API documentation can be found on: https://ekzhu.github.io/datasketch/documentation.html
