### ISSUE TITLE
Return maximum number of elements

### ISSUE THREAD

**Issue by wouterMostard** [ekzhu/datasketch#90]
Hi all,

Is there a way to return only a user specified number of elements is returned? Currently I am working in a database with potentially millions of similar elements, which is vastly slowing the query. I could ofcourse use an LSHforest but sadly there is no persistency available.

Cheers,

Wouter

**Comment by ekzhu** [comment]
This is a good feature suggestion. However I would say if your number of elements is too large, maybe you should use a higher threshold.

**Comment by wouterMostard** [comment]
Thank you for your response, setting a higher threshold value could lead to more false negatives, something we want to avoid. I will fork the project and look if I can add a feature for retrieving maximum N elements.

**Comment by ekzhu** [comment]
I see. Do you require the index to return the best N elements, or any N-element subset of all the elements that would be returned by the index?

**Comment by wouterMostard** [comment]
For my use case, yes this holds. Thank you for the suggestion for breaking the loop after N elements, this would greatly increase speed when the number of near duplicates would be in the thousands.

**Comment by ekzhu** [comment]
Thanks! Close the issue.
