### ISSUE TITLE
Combining/Storing LSH with different thresholds

### ISSUE THREAD

**Issue by NThakur20** [ekzhu/datasketch#93]
Hi, 

First of all thanks for this amazing package. I have two LSH, one optimized with a threshold of 0.65 and the other with a threshold of 0.55. I found the results from both these LSH are relevant to me, and I would finally take a union of the results of both of these, and get my duplicate contents. 

In order to store both LSH, I'm using Redis caching mechanism, but later I will have to call both the LSH, run individually and take the union of the results. 

Is there any way I could optimize so that I could do the same with only one LSH if possible or some method to create a special type of indexes in Redis such that I don't have to call the LSH's Individually. This would help me save Memory and Computational Time.

**Comment by ekzhu** [comment]
How did you compare the results of thresholds 0.65 and 0.55? The result of 0.55 should be approximately a super set of the result of 0.65. Ideally you only need one index with 0.55.

**Comment by NThakur20** [comment]
Hi ekzhu, so even I thought the set of 0.55 should be a superset but when I compared results of both some of the results which came with a threshold of 0.65 didn't appear with the 0.55 one. These exceptions were relevant to me hence I planned on using both the thresholds.
Is this scenario normal? Has anyone faced this before.

**Comment by aastafiev** [comment]
This behavior is normal, because it’s an approximate nearest neighbor algorithm. You could try to play with number of permutations on hash function.


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by NThakur20** [comment]
@aastafiev Yes I could play around with the number of permutations on hash function but is there any possibility of combining the LSH's together?

**Comment by NThakur20** [comment]
@aastafiev Also if possible if you can mention a basic example of how to change the number of permutations on hash function. I wasn't able to understand from the documentation directly how to give the permutations as an input.

**Comment by aastafiev** [comment]
There is no possibility to combine LSH together. You can create different instances of it and combine them in your application. Before using MinHashLSH you can create MinMash'es with as much permutations as you need. See [doc](https://ekzhu.github.io/datasketch/documentation.html#minhash). Moreover, you can use another kind of hashfunc to improve speed and precision.

**Comment by NThakur20** [comment]
Okay, thanks a lot will look into this.
