### ISSUE TITLE
Storing in redis requires large amount of memory. 

### ISSUE THREAD

**Issue by wouterMostard** [ekzhu/datasketch#95]
Hi all, thanks again for the superb implementation of minhash. Currently I have ~200 million documents I would like to store while keeping the memory footprint as low as possible. I extracted a subset of 150k documents and generated 32bit hashes, resulting in a redis-db having the following size:

```
# Memory
used_memory:305137856
used_memory_human:291.00M
used_memory_rss:328646656
used_memory_rss_human:313.42M
used_memory_peak:937872680
```

So these 150k hashes take up around 300 mb. This would be a way too large memory footprint if I assume that the size will increase linearly (to be honest I do not know how the hashes are stores), taking up  > 150gb RAM in redis. If I look at the size of the object in python however the size is only 56 bytes. In this case 5.2gb would suffice. 

Could you give some pointers on how I could store 200 million documents with 100gb RAM? Or is some other sort of database layer required for this?

Thank you in advance!

Wouter

**Comment by ekzhu** [comment]
Storing the hashes in redis will incur overhead such as indexes etc. Maybe you can look into Redis configurations to see how you can optimize this. 200 M documents is not a small number. I am curious about this scenario. Could you tell us more about it?

1. What's the reason for keeping all the documents signatures in memory? Have you tried simply serialize and store the hashes into a disk-based database (such as postgres), and read it out when needed? It would be just a little bit slower but suffice for most applications, especially if SSD is used.
2. Are your hashes frequently updated?
3. 256 GB RAM is about [1300](https://www.newegg.com/p/pl?d=256gb+ram), doesn't seems too bad if the use case is important to you.

**Comment by wouterMostard** [comment]
Thanks for your quick response! The use case is a monthly scrape of hostnames. In order to quickly determine whether we want to scrape the entire website or only parts we want to be able to detect near duplicates. If the number of near duplicates is above a certain threshold, say 100, there is probably no interesting information and we skip  the hostname. All hostnames that have > 100 similar hostnames are not stored to save some space. This helps to prevent storing 50 million placeholder websites 

1. The reason is that we do not know which hostnames are near duplicates of another, so there is no possibility for us to only retrieve the hash of a hostname when we need it. I am currently looking into making a MySQL persistency layer for your library. I found some code of a different repository of yours that made use of Postgres and written in Go, maybe I could port that part for my use in this library? 

2. No, the hashes are updated once a month

3. Getting a bigger machine could be the solution, maybe even shard the data across multiple machines. I think Redis supports this, but first I want to see whether it is possible to get the algorithm to work with the current machine that we have.

**Comment by ekzhu** [comment]
Have you tried reducing `num_perm`? Say `num_perm=64` -- it will save 1/2 memory usage. This may reduce some accuracy, but depending on your data it may not matter.

**Comment by ekzhu** [comment]
Close due to inactivity.
