### ISSUE TITLE
LeanMinHash does not save memory in Redis

### ISSUE THREAD

**Issue by jeanjluo** [ekzhu/datasketch#96]
I am using Redis to store the MinHashLSH hashes. The input data is only 223MB, but MinHashLSH resulted in over 15G memory usage in Redis. I attempted to use LeanMeanHash to reduce the memory footprint, but surprisingly it resulted in 16.54G memory usage. Why did LeanMinHash lead to a higher memory usage?

Below is the code snippet with LeanMeanHash. I am not sure if I was using LeanMinHash correctly.

```
def mh(str):
    m = MinHash(num_perm=128)
    for c in set(str):
        m.update(c.encode('utf8'))
    return LeanMinHash(m)

def insert(lsh, df):
    with lsh.insertion_session() as session:
            session.insert(key, mh(value), check_duplication=True)
```

**Comment by aastafiev** [comment]
This is normal, because of storage structure. If you don’t have enough memory you could try other types of storages.


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by ekzhu** [comment]
Another note, if the set sizes in the input data are not large, you can reduce the `num_perm` to save memory. e.g., use `num_perm=64` will save 1/2 memory from the default setting.

**Comment by jeanjluo** [comment]
Thank you for the suggestions. I will try reducing the num_perm. I am also wondering if Datasketch currently supports or plans to support Redis Cluster, so that the work load can be automatically spread across multiple nodes?

**Comment by ekzhu** [comment]
Not right now. In a sense, datasketch is built to use little resource as possible with fast setup time. If the use case involves a lot of resource, maybe it makes more sense to use the conventional exact techniques.
