### ISSUE TITLE
Containment value from MinHashLSHEnsemble

### ISSUE THREAD

**Issue by mbhall88** [ekzhu/datasketch#97]
Forgive me if this is a stupid question, but is it possible to get the containment measure for each key compared to the query MinHash in a MinHash LSH Ensemble?  

For example, say I have twelve different sets in my Ensembl and for a given query MinHash I want to be able to say which of the twelve sets my query is most like (and comparing containment values seems the most sensible way to do this). But I cant see from the API or the code where I would get this value from?  

 Part of the reason I am using the Ensemble is each of my queries is potentially much bigger than any of the twelve sets in the Ensemble. Or should I be trying a different approach here?

**Comment by ekzhu** [comment]
The LSH Ensemble (just like MinHashLSH), does not compute the exact containment. So once you get the keys, you can retrieve the actual sets and compute containment exactly.

If your query set is much bigger than the indexed sets, then the containment (computed as the intersection size divided by query set size) is going to be quite small regardless of how much intersection there is. You can try use a small threshold and see if the accuracy is acceptable.

**Comment by citynorman** [comment]
Can you get approximate containment? Or at least a ranking?

**Comment by ekzhu** [comment]
You can do it with MinHashes as a post-processing step.

**Comment by du-phan** [comment]
Hello @ekzhu , late to the party but you can elaborate more how can you use MinHash as post-processing step to estimate containment ? Thanks!
